capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('smite/', include('smite.urls')),
    path('admin/', admin.site.urls),
]

capstone/smite/urls.py
from django.urls import path

from . import views

app_name = 'smite'
urlpatterns = [
    path('', views.index, name='index'),
    path('gods/', views.gods, name='gods'),
    path('items/', views.items, name='items'),
    path('player/<str:player>/<str:name>/', views.player, name='player'),
    path('search_player/',
         views.search_player, name='search_player'),
    path('search_results/<str:player>/',
         views.search_results, name='search_results'),
    path('god/<str:r_Name>/', views.god, name='god'),
    path('match/<int:match>/', views.get_match, name='get_match'),
    path('skins/<str:name>/<int:id>/', views.skins, name='skins'),
    path('checkapi/', views.check, name='check_api'),
]

capstone/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'smite/index.css' %}">

  <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nanum+Myeongjo&display=swap" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>{% block title %}Smite.io{% endblock %}</title>
</head>
<body>
  <article>
    <header class="header">
      <nav class="navbar">
        <div class="hamburger">
          <span class="bar"></span>
          <span class="bar"></span>
          <span class="bar"></span>
      </div>
          <a href="{% url 'smite:index' %}" class="nav-logo">Smite.io</a>
          <ul class="nav-menu">
              <li class="nav-item">
                  <a href="{% url 'smite:gods' %}" class="nav-link">Gods</a>
              </li>
              <li class="nav-item">
                  <a href="{% url 'smite:items' %}" class="nav-link">Items</a>
              </li>
          </ul>
          
      </nav>
</header>
    <main>
      {% block content %}
      
      {% endblock %}
    </main>
    
  </article>
  <script>
    const hamburger = document.querySelector(".hamburger");
    const navMenu = document.querySelector(".nav-menu");

    hamburger.addEventListener("click", mobileMenu);

    function mobileMenu() {
        hamburger.classList.toggle("active");
        navMenu.classList.toggle("active");
    }

    
  </script>
</body>
</html>