capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('smite/', include('smite.urls')),
    path('admin/', admin.site.urls),
]

capstone/smite/urls.py
from django.urls import path

from . import views

app_name = 'smite'
urlpatterns = [
    path('', views.index, name='index'),
    path('gods/', views.gods, name='gods'),
    path('items/', views.items, name='items'),
    path('player/<str:player>/<str:name>/', views.player, name='player'),
    path('search_player/',
         views.search_player, name='search_player'),
    path('search_results/<str:player>/',
         views.search_results, name='search_results'),
    path('god/<str:r_Name>/', views.god, name='god'),
    path('match/<int:match>/', views.get_match, name='get_match'),
    path('skins/<str:name>/<int:id>/', views.skins, name='skins'),
    path('checkapi/', views.check, name='check_api'),
]

capstone/smite/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.


class Skin(models.Model):
    god_icon_url = models.URLField()
    god_skin_url = models.URLField()
    god_name = models.CharField(max_length=30)
    god_id = models.IntegerField()

    def __str__(self):
        return_str = self.god_name + self.god_skin_url
        return return_str


class Session(models.Model):
    getter_id = models.IntegerField()
    session_id = models.CharField(max_length=100)

    def __str__(self):
        return self.session_id


class God(models.Model):
    gods = models.JSONField()


class Item(models.Model):
    items = models.JSONField()

capstone/smite/views.py
import asyncio
from smite.models import Skin, Session, God, Item
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from datetime import datetime, timedelta
import requests
import hashlib
import json
with open('hide.json') as f:
    data = json.load(f)
dev_id = data['DEV_ID']
auth_key = data['AUTH_KEY']

# Create your views here.


def index(request):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')

    session_id = Session.objects.get(getter_id=1)

    signature = f'{dev_id}testsession{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    test_response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/testsessionjson/{dev_id}/{signature_hashed}/{session_id}/{date}').json()

    if (test_response.startswith('Invalid session id')):
        print('created session')
        signature = f'{dev_id}createsession{auth_key}{date}'
        signature_hashed = hashlib.md5(signature.encode()).hexdigest()
        response = requests.get(
            f'https://api.smitegame.com/smiteapi.svc/createsessionjson/{dev_id}/{signature_hashed}/{date}').json()

        Session.objects.all().delete()
        sess = Session(getter_id=1, session_id=response['session_id'])
        sess.save()

    else:
        response = test_response

    context = {'dev': dev_id, 'auth': auth_key,
               'hashed': signature_hashed, 'time': date, 'res': response, 'sess': session_id}
    return render(request, 'smite/index.html', context)


def gods(request):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    day = datetime.now()
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getgods{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    if day.weekday() == 1 and day.hour == 14 and day.minute == 31:
        God.objects.all().delete()
        response = requests.get(
            f'https://api.smitegame.com/smiteapi.svc/getgodsjson/{dev_id}/{signature_hashed}/{session_id}/{date}/1').json()
        save_response_to_gods = God(gods=response)
        save_response_to_gods.save()
        print('updated gods')
    else:
        response = God.objects.first().gods
        print('gods from database')

    context = {'gods': response, 'sess': session_id}
    return render(request, 'smite/gods.html', context)


def items(request):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    day = datetime.now()
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getitems{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()

    if day.weekday() == 1 and day.hour == 14 and day.minute == 31:
        Item.objects.all().delete()
        response = requests.get(
            f'https://api.smitegame.com/smiteapi.svc/getitemsjson/{dev_id}/{signature_hashed}/{session_id}/{date}/1').json()
        save_response_to_items = Item(items=response)
        save_response_to_items.save()
        print('updated items')
    else:
        response = Item.objects.first().items
        print('items from database')

    test_img = ['Mail of Renewal (old)', "Manticore's Spikes", "Sphinx's Baubles", '*Hand of the Gods', 'Stone of Fal (old)', '*War Flag', "Lono's Mask (deprecated)", 'S7 Staff of Myrddin', 'S8 Meditation Cloak', 'S8 Magic Shell',
                'z* S7 Sundering Spear', 'S8 Phantom Vei', 'S8 Meditation Cloak Upgrade', 'S8 Phantom Veil', 'S8 Phantom Veil Upgrade', 'S8 Magic Shell Upgrade', 'z* Sundering Spear Upgrade']
    context = {'res': response, 'test_img': test_img, 'sess': session_id}
    return render(request, 'smite/items.html', context)


def search_player(request):
    player = request.POST.get('player')
    return HttpResponseRedirect(reverse('smite:search_results', args=(player,)))


def search_results(request, player):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}searchplayers{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    players = []
    response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/searchplayersjson/{dev_id}/{signature_hashed}/{session_id}/{date}/{player}').json()
    for r in response:
        sig = f'{dev_id}getplayer{auth_key}{date}'
        signature_h = hashlib.md5(sig.encode()).hexdigest()
        p = requests.get(
            f'https://api.smitegame.com/smiteapi.svc/getplayerjson/{dev_id}/{signature_h}/{session_id}/{date}/{r["player_id"]}').json()

        players.append(p[0])
    context = {'player': players, 'sess': session_id}
    return render(request, 'smite/search_results.html', context)


def player(request, player, name):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getplayer{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/getplayerjson/{dev_id}/{signature_hashed}/{session_id}/{date}/{player}').json()

    signature = f'{dev_id}getmatchhistory{auth_key}{date}'
    signature_h = hashlib.md5(signature.encode()).hexdigest()
    response_history = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/getmatchhistoryjson/{dev_id}/{signature_h}/{session_id}/{date}/{player}').json()
    conquest_mmr = int(response[0]['Rank_Stat_Conquest_Controller'])
    joust_mmr = int(response[0]['Rank_Stat_Joust_Controller'])
    player_name = response[0]['Name']
    if ']' in player_name:
        player_name = player_name.partition(']')[2]

    context = {'player': response[0],
               'history': response_history, 'name': player_name, 'jmmr': joust_mmr, 'cmmr': conquest_mmr, 'sess': session_id}
    return render(request, 'smite/player.html', context)


def get_match(request, match):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getmatchdetails{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/getmatchdetailsjson/{dev_id}/{signature_hashed}/{session_id}/{date}/{match}').json()
    match_id = match
    check_name = ''
    get_time = response[0]['Time_In_Match_Seconds']
    time = timedelta(seconds=get_time)
    context = {'match': response, 'time': time, 'match_id': match_id,
               'check_name': check_name, 'sess': session_id}
    return render(request, 'smite/match.html', context)


def god(request, r_Name):
    session_id = Session.objects.get(getter_id=1)
    gods = God.objects.first().gods
    god = {}
    for g in gods:
        if g['Name'] == r_Name:
            god = g
    context = {'res': gods[0], 'sess': session_id, 'god': god}
    return render(request, 'smite/god.html', context)


def check(request):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getdataused{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/getdatausedjson/{dev_id}/{signature_hashed}/{session_id}/{date}').json()

    context = {'res': response[0], 'sess': session_id}
    return render(request, 'smite/checkapi.html', context)


def skins(request, name, id):
    date = datetime.utcnow().strftime('%Y%m%d%H%M%S')
    session_id = Session.objects.get(getter_id=1)
    signature = f'{dev_id}getgodskins{auth_key}{date}'
    signature_hashed = hashlib.md5(signature.encode()).hexdigest()
    response = requests.get(
        f'https://api.smitegame.com/smiteapi.svc/getgodskinsjson/{dev_id}/{signature_hashed}/{session_id}/{date}/{id}/1').json()
    skin_list_exclude = ['Diamond', 'Legendary',
                         'Shadow', 'Happy Little Painter']
    context = {'skins': response, 'name': name, 'skin_list': skin_list_exclude}
    return render(request, 'smite/skins.html', context)

capstone/smite/templates/smite/checkapi.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'smite/index.css' %}">
    <title>Document</title>
</head>
<body>
    <div>
        active sessions: {{res.Active_Sessions}}<br/>
        concurrent sessions: {{res.Concurrent_Sessions}}<br/>
        request limit daily: {{res.Request_Limit_Daily}}<br/>
        session cap: {{res.Session_Cap}}<br/>
        session time limit: {{res.Session_Time_Limit}}<br/>
        total request today: {{res.Total_Requests_Today}}<br/>
        sessions today: {{res.Total_Sessions_Today}}<br/>
        ret_msg: {{res.ret_msg}}<br/>
    </div>
</body>
</html>

capstone/smite/templates/smite/god.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'smite/index.css' %}">
    <title>Document</title>
</head>
<body>
    {{sess}}<hr>
    {{god}}
    <h1>{{god.Name}}</h1>
    <h4>{{god.Title}}</h4>
    <h5>{{god.Roles}}</h5>
    <h5>{{god.Pantheon}}</h5>
    <h5>{{god.Type}}</h5>
    <h5>{{god.Type}}</h5>
    <hr>
    <h5>{{god.Ability1}}</h5>
    <img src={{god.Ability_1.URL}} alt="">
    <h5>{{god.Ability2}}</h5>
    <img src={{god.Ability_2.URL}} alt="">
    <h5>{{god.Ability3}}</h5>
    <img src={{god.Ability_3.URL}} alt="">
    <h5>{{god.Ability4}}</h5>
    <img src={{god.Ability_4.URL}} alt="">
    <h5>Passive: {{god.Ability5}}</h5>
    <img src={{god.Ability_5.URL}} alt="">
</body>
</html>

capstone/smite/templates/smite/gods.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div id="gods-page">
<div class="page-title">
    <h4>GODS</h4>
</div>
<div class="select_filter">
<select name="filter" id="filter" v-model="filter">
    <option for="All">All</option>
    <option for="Mage">Mage</option>
    <option for="Assassin">Assassin</option>
    <option for="Hunter">Hunter</option>
    <option for="Warrior">Warrior</option>
    <option for="Guardian">Guardian</option>
</select>
</div>
<div id="gods">
    <div v-for="god in gods">
        <div v-if="god.Roles == filter">
        <a class="god_link" :href=`/smite/skins/${god.Name}/${god.id}/`>
        <div class="god" >
            <img :src="god.godCard_URL" alt="">
            <div class="god-details">
            <div class="god-details-name">[[god.Name]]</div>
            <div class="god-details-title">[[god.Title]]</div>
            <p class="pros">[[god.Roles]] [[god.Type]]</p>
            </div>
        </div>
    </a>
    </div>
    <div v-if="filter == 'All'">
        <a class="god_link" :href=`/smite/skins/${god.Name}/${god.id}/`>
        <div class="god" >
            <img :src="god.godCard_URL" alt="">
            <div class="god-details">
            <div class="god-details-name">[[god.Name]]</div>
            <div class="god-details-title">[[god.Title]]</div>
            <p class="pros">[[god.Roles]] [[god.Type]]</p>
            </div>
        </div>
    </a>
    </div>
</div>
</div>
</div>

{{ gods|json_script:'all-gods' }}
<script>

    const getGods = JSON.parse(document.getElementById('all-gods').textContent)
    new Vue({
        el: "#gods-page", 
        delimiters: ['[[',']]'],
        data: {
            gods: getGods,
            filter: 'All',
        },
        
    })
</script>
{% endblock %}

capstone/smite/templates/smite/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="index-background">
    
<div class="page-title-index">
    <h4></h4>
</div>

        
        <div class="index">
            <h1 class="under">Search Player</h1>
            <h1 class="over">Search Player</h1>
            <div class="form-container">
            <form action="{% url 'smite:search_player' %}" method="post">
                {% csrf_token %}
                
                <input type="text" name="player" id="player" placeholder="Player Name"/>
                
                <button type="submint"><img src="{% static 'smite/icons8-search-26.png' %}" alt=""></button>
                
                
            </form>
        </div>
            
        </div>
</div>
{% endblock %}

capstone/smite/templates/smite/items.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="page-title">
    <h4>ITEMS</h4>
</div>
<div id="items">
    <div class="select_filter">
        <select name="filter" id="filter" v-model="filter">
            <option for="All">All</option>
            <option for="MagicalPower">Magical Power</option>
            <option for="PhysicalPower">Physical Power</option>
            <option for="MagicalProtection">Magical Protection</option>
            <option for="PhysicalProtection">Physical Protection</option>
            <option for="MagicalPenetration">Magical Penetration</option>
            <option for="PhysicalPenetration">Physical Penetration</option>
        </select>
        </div>
    <div v-for="item in sortItem">
        <a class="item_link" :href=`#`>
            <div class="item" >
                <img :src="item.itemIcon_URL" alt="">
                <div class="item-details">
                <div class="item-details-name">[[item.DeviceName]]</div>
                <div class="item-details-title"></div>
                </div>
            </div>
        </a>
    </div>
</div>
</div>

{{ res|json_script:'all-items' }}
{{ test_img|json_script:'test_img' }}
<script>

    const getItems = JSON.parse(document.getElementById('all-items').textContent)
    const test_img = JSON.parse(document.getElementById('test_img').textContent)
    new Vue({
        el: "#items", 
        delimiters: ['[[',']]'],
        data: {
            items: [],
            testImgList: test_img,
            filter: 'All',
            itemsByType: [],
        },
        mounted(){
            this.getItemsWithImg()
        },
        methods: {
            getItemsWithImg(){
                getItems.forEach(e => {
                    if(this.testImgList.indexOf(e.DeviceName) === -1){
                        this.items.push(e)
                    }
                });
            },

        },
        computed:{
            sortItem(){
                var item = this.items.filter((e) => {
                    if(this.filter == 'All'){
                        return true
                    }else if(e.ItemDescription.Menuitems[1]){
                        if(e.ItemDescription.Menuitems[0].Description.includes(this.filter) || e.ItemDescription.Menuitems[1].Description.includes(this.filter)) 
                            return true
                    }
                })
                return item
            }
        }
    })
</script>
{% endblock %}

capstone/smite/templates/smite/match.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="page-title">
    <h4>Match</h4>
</div>
<div class="match_id">
<h5>Id: {{match_id}}</h5>
<h5>Time: {{time}}</h5>
</div>
<div class="match_stats_container">
    <div class="stats_container">
    <div class="match_title">
        <div class="match_player_div">Player</div>
        <div class="match_player_god">God</div>
        <div class="match_player_kda">KDA</div>
        <div class="match_player_s">Damage</div>
    </div>
    {% for m in match %}
        {% if m.TaskForce == 1 %}
            <div class="match_team_1">
                {% if m.playerName != check_name %}
                <div class="player_div"><a href="{% url 'smite:player' player=m.playerId name=m.playerName %}">{{m.playerName}}</a></div>
                <div class="player_god">{{m.Reference_Name}}</div>
                <div class="player_kda">{{m.Kills_Player}}/{{m.Deaths}}/{{m.Assists}}</div>
                <div class="player_s">{{m.Damage_Player}}</div>
                {% else %}
                <div class="player_div">*PA*</div>
                <div class="player_god">{{m.Reference_Name}}</div>
                <div class="player_kda">{{m.Kills_Player}}/{{m.Deaths}}/{{m.Assists}}</div>
                <div class="player_s">{{m.Damage_Player}}</div>
                {% endif %}
            </div>
        {% endif %}
        {% if m.TaskForce == 2 %}
            <div class="match_team_2">
                {% if m.playerName != check_name %}
                <div class="player_div"><a href="{% url 'smite:player' player=m.playerId name=m.playerName %}">{{m.playerName}}</a></div>
                <div class="player_god">{{m.Reference_Name}}</div>
                <div class="player_kda">{{m.Kills_Player}}/{{m.Deaths}}/{{m.Assists}}</div>
                <div class="player_s">{{m.Damage_Player}}</div>
                {% else %}
                <div class="player_div">*PA*</div>
                <div class="player_god">{{m.Reference_Name}}</div>
                <div class="player_kda">{{m.Kills_Player}}/{{m.Deaths}}/{{m.Assists}}</div>
                <div class="player_s">{{m.Damage_Player}}</div>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
</div>
<p>*PA*: Private account names are hidden.</p>
</div>
{% endblock %}

capstone/smite/templates/smite/player.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="page-title">
    <h4>{{name}}</h4>
</div>
<div class="match_stats_container">
    <div class="player_stats">
        <div class="history_title">
            <div class="match_player_div">Hours</div>
            <div class="match_player_god">Level</div>
            <div class="match_player_kda">Last Seen</div>
        </div>
        <div class="history_detail">
            <div class="history_title_1">{{player.HoursPlayed}}</div>
            <div class="history_title_2">{{player.Level}}</div>
            <div class="history_title_3">{{player.Last_Login_Datetime}}</div>
            
        </div>
        <div class="history_title_two">
            <div class="match_player_div">Platform</div>
            <div class="match_player_god">Ranked Conquest</div>
            <div class="match_player_kda">Ranked Joust</div>
        </div>
        <div class="history_detail_end">
            <div class="history_title_1">{{player.Platform}}</div>
            <div class="history_title_2">{{cmmr}}</div>
            <div class="history_title_3">{{jmmr}}</div>
            
        </div>
    </div>
</div>
<div class="match_history_title">
    <h5>Match History</h5>
</div>
    <div class="match_stats_container">
    <div class="match_history">
    {% for match in history %}
    <div class="link_wrapper">
        <a href="{% url 'smite:get_match' match=match.Match %}">
            
                <div class="history_title">
                    <div class="history_god">God</div>
                    <div class="history_mode">Mode</div>
                    <div class="history_kda">K/D</div>
                </div>
                <div class="history_detail_end">
                    <div class="history_title_1">{{match.God}}</div>
                    <div class="history_title_2">{{match.Map_Game}}</div>
                    <div class="history_title_3">{{match.Kills}}/{{match.Deaths}}</div>
                    
                </div>
            
        </a>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}

capstone/smite/templates/smite/search_player.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'smite/index.css' %}">
    <title>Document</title>
</head>
<body>
    {{sess}}<hr>
    {{player}}
</body>
</html>

capstone/smite/templates/smite/search_results.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="page-title">
    <h4>{{name}} Player Results</h4>
</div>
<div id="player_results">
    <div id="gods" class="search_results_players">
        {% for p in player %}
            <div>
                <div class="player-results" >
                    <a href="{% url 'smite:player' player=p.Id name=p.Name %}" id="player_card">
                        {{p.Name}}
                        <ul class="player-result-list">
                            <li>Platform: {{p.Platform}}</li>
                            <li>Hours: {{p.HoursPlayed}}</li>
                            <li>Last Seen: {{p.Last_Login_Datetime}}</li>
                        </ul>
            
                   
                </a>
                </div>
            </div>
    {% endfor %}
</div>
</div>
{% endblock %}

capstone/smite/templates/smite/skins.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block title %}Smite{% endblock %}

{% block content %}
<div class="page-title">
    <h4>{{name}} Skins</h4>
</div>
<div id="gods">
    {% for skin in skins %}
        {% if skin.skin_name not in skin_list %}
        <div>
            <div class="god" >
                <img src="{{skin.godSkin_URL}}" alt="">
                <div class="god-details">
                <div class="god-details-name">{{skin.skin_name}}</div>
                <div class="god-details-title">{{skin.obtainability}}</div>
            </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
</div>

{% endblock %}